default: &default
  adapter:  postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  encoding: unicode
  pool:     5
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  template: template0

development:
  <<: *default
  database: teamPokedex_development

test:
  <<: *default
  database: teamPokedex_test

production:
  <<: *default
  database: teamPokedex_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD_PRODUCTION"] %>